package com.doviesfitness.utils

class StringConstant {
    companion object{
        val success = "success"
        val next_page = "next_page"
        val settings = "settings"
        val count = "count"
        val message = "message"
        val data = "data"
        val is_available = "is_available"
        val Android = "Android"
        val FB = "FB"

        val profile_pic = "profile_pic"
        val auth_customer_id = "auth_customer_id"
        val custom_notification_id = "custom_notification_id"
        val device_id = "device_id"
        val device_token = "device_token"
        val device_type = "device_type"

        val page_index = "page_index"
        val diet_plan_category_id = "diet_plan_category_id"
        val diet_plan_id = "diet_plan_id"
        val workout_id = "workout_id"
        val added_by_type = "added_by_type"

        val newsFeed = "NEWSFEED"
        val exercise = "EXERCISE"
        val workout = "WORKOUT"
        val module_name = "module_name"
        val module_id = "module_id"
        val comment_text = "comment_text"
        val authToken = "AUTHTOKEN"
        val workout_group_id = "workout_group_id"
        val filter_level = "filter_level"
        val filter_exercises = "filter_exercises"
        val filter_tags = "filter_tags"
        val filter_body_part = "filter_body_part"
        val filter_equipments = "filter_equipments"
        val filter_good_for = "filter_good_for"
        val accept = "Accept"
        val HBDEV = "HBDEV"
        val contentType = "Content-Type"


        val news_id = "news_id"
        val group_id = "group_id"
        val comment_id = "comment_id"
        val report_text = "report_text"
        val program_id = "program_id"
        val apiKey = "APIKEY"
        val apiVersion = "APIVERSION"
        val type = "type"
        val notificationId = "notificationId"
        val module_type = "module_type"
        val filter_category = "filter_category"
        val auth_customer_subscription = "auth_customer_subscription"
        val exercise_id = "exercise_id"
        val workout_log_id = "workout_log_id"
        val email = "email"
        val password = "password"
        val user_name = "user_name"
        val newPassword = "new_password"
        val oldPassword = "old_password"
        val newConfirmPassword = "new_confirm_password"
        val deviceToken = "device_token"
        val deviceType = "device_type"
        val apiVersionValue = "1"
        val applicationJson = "application/json"
        val packageMasterId = "package_master_id"
        val platformType = "platform_type"
        val paymentPlatformType = "payment_platform_type"
        val packageName = "package_name"
        val platformProductId = "platform_product_id"
        val transactionDetail = "transaction_detail"
        val purchaseToken = "purchase_token"
        val purchaseAuthToken = "auth-token"
        val AuthToken1 = "auth-token"
        val quantity = "quantity"
        val productId = "product_id"
        val transactionId = "transaction_id"
        val encodedKey = "encoded_key"
        val limit = "limit"
        val offset = "offset"
        val logId = "log_id"
        val date = "date"
        val historyId = "history_id"

    }
}